version: '3'
tasks:
  migrate:*:
    vars:
      ACTION: '{{index .MATCH 0}}'
    env:
      GOOSE_DRIVER: sqlite3
      GOOSE_DBSTRING: ./database.db
      GOOSE_MIGRATION_DIR: ./migration
    cmds:
      - goose {{.ACTION}} {{.CLI_ARGS}} sql
